/*
 * minisort - sort the records in the file generated by the program 'gen_sort'
 *            according to the 'key' (the first 10 bytes) of each record. the result 
 *            is ascending order of charactors. If the key of multiple records are 
 *            the same, the record with small record number is prior.
 */
#include <stdio.h>
#include <stdlib.h>
char* data[2000010];
static void usage(char *fn)
{
    /* 
     * NOTE: the 'input_filename' is neccessary, and the output_filename is optional 
     * if the user don't provide output_filename, then minisort print the result to screen
     */
    printf("usage: %s <input_filename> [output_filename]\n", fn);
}
long fileSize(FILE *fin){
    long int savedPos;
    long size;
    savedPos=ftell(fin);
    fseek(fin,0L,SEEK_END);
    size=ftell(fin);
    fseek(fin,savedPos,SEEK_SET);
    return(size);
}
// the compare function
int comp(char* x,char* y){
    for (;*x==*y;x++,y++);
    return (*x-*y);
}
// quicksort
void sort(int l,int h){
if (h<l+2) return;
    int p=l,e=h;
    while (l<h) {
	while (++l<e && (comp(data[p],data[l])>0));
	while (--h>p && (comp(data[h],data[p])>0));
     	if (l<h){
	    char* temp=data[l];
	    data[l]=data[h];
	    data[h]=temp;	
	}
    }
    char* temp=data[h];
    data[h]=data[p];
    data[p]=temp;
    sort(p,h);
    sort(l,e);
}
int main(int argc, char *argv[])
{
    if (argc < 2) {
        usage(argv[0]);
        exit(EXIT_FAILURE);
    }
    /* check and get the arguments */
    FILE* fin;
    FILE* fout;
    fin=fopen(argv[1],"r");
    if (argc==3){
        fout=fopen(argv[2],"w");
    } 
    else fout=stdout;
    if (fin==NULL){
	printf("Minisort: Error! Failed to open '%s' file.\n",argv[1]);
	return 0;
    }
    long sum=fileSize(fin);    
    printf("Minisort: The size of '%s' file is 0x%lx bytes.\n",argv[1],sum);
    if (sum>0x5f5e100) printf("Minisort: Warning!The size of '%s' file may be too large. (Larger than 100Mbytes)\n",argv[1]);
    if (sum>0xbebc200){
    	printf("Minisort: Error! The size of '%s' file is too large. (Larger than 200Mbytes.)\n",argv[1]);
    	return 0;
    }
    //Check the size of the file.
    if (sum%100!=0){
    	printf("Minisort: Error! file format is invalid. (fsize 0x%lx)\n",sum);
	return 0;
    }
    int top=0;
    char* dat=malloc(sum+1000); //Allocate the memory.
    if (dat==NULL) {printf("Minisort: Error! Malloc error occurs. "); return 0;}
    data[0]=dat;
    //get the strings
    while (fread(data[top],100,1,fin)!=0){        
	top++;
        data[top]=dat+top*100;
	if (data[top]==NULL){
	   printf("Minisort: Error! Malloc error occurs. ");
	   return 0;	
	} 
    }    
    /* check and get input file
     * the size of input file should be the multiple of record size (100 bytes)
     */
    printf("Minisort: Start to sort %d records...\n",top);
    //qsort
    sort(0,top); 
    printf("Minisort: Done.\n");	
    /* do sort */
    if (argc==2) {printf("\n"); printf("Results (%d records):\n",top);}
    //Write the data to the file or print it on the console
    int i;
    for (i=0;i<top;i++){
    	fwrite(data[i],100,1,fout);
    }	    
    if (argc==3){
    	printf("Minisort: Success to write result. (%d records)\n",top);
    }
    /* print the result to screen or output file */
    free(dat);
    fclose(fin);
    fclose(fout);
    /* release allocated resource */
    return 0;
}


